[package]
name = "learn__crate__mongodb"
version = "0.1.0"
edition = "2018"


[dependencies]
mongodb = { version = "2.0.0-beta.2", default-features = false, features = ["sync"] }
serde = {version="1", features=["derive"]}