[package]
name = "learn__crate__mongodb"
version = "0.1.0"
edition = "2018"


[dependencies]
mongodb = { version = "2.0.1", default-features = false, features = ["sync"] }
serde = "1.0.130"
serde_json = "1.0.68"
chrono = { version = "0.4.19", features = ["serde"] }